Inscription jumelage mix - Mise en commun
dinfcll/sachem pull request #71
Opened 2016-12-02 13:59 UTC by DylanMarcotte

Fixes pour bugs, mise en commun

2016-12-02 14:05 UTC, olafleur commented on sachem/Classes_Sachem/ValidationsAcces.cs
> +                    filterContext.Result = new RedirectResult("/Account/Login");
`{ }`

2016-12-02 14:05 UTC, olafleur commented on sachem/Classes_Sachem/ValidationsAcces.cs
> +                    filterContext.Result = new RedirectResult(PATH_ERREUR_AUTH);
ici aussi

2016-12-02 14:05 UTC, olafleur commented on sachem/Classes_Sachem/ValidationsAcces.cs
> +                    filterContext.Result = new RedirectResult(PATH_ERREUR_AUTH);
ici aussi

2016-12-02 14:05 UTC, olafleur commented on sachem/Classes_Sachem/ValidationsAcces.cs
> +                    filterContext.Result = new RedirectResult(PATH_ERREUR_DEJA);
ici

2016-12-02 14:06 UTC, olafleur commented on sachem/Controllers/HomeController.cs
>  }
nl eof

2016-12-02 14:07 UTC, olafleur commented on sachem/Controllers/InscriptionController.cs
> +                    case 4: //Tuteur de rémunéré
Tuteur ~~de~~ rémunéré

2016-12-02 14:11 UTC, olafleur commented on sachem/Controllers/InscriptionController.cs
> +            List<string> Jours = new List<string>();
98 à 104 peuvent être remplacés par :
`return new List<string>{ "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi" };`

2016-12-02 14:11 UTC, olafleur commented on sachem/Controllers/InscriptionController.cs
> +            //string[] jour = new string[5] { "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi" };
code en commentaire !!!!

2016-12-02 14:12 UTC, olafleur commented on sachem/Controllers/InscriptionController.cs
>          //NOTE: Penser à Wiper les inscriptions à chaque fin de session. Constante?
C'est pas clair ce que ce commentaire dit.

2016-12-02 14:14 UTC, olafleur commented on sachem/Models/DisponibiliteStruct.cs
> +            dictionary = new Dictionary<string, int>();
15 à 20 peuvent être remplacées par : 
`dictionary = new Dictionary<string, int> { { "Lundi", 2 }, {"Mardi", 3 }, etc. };`

2016-12-02 14:16 UTC, olafleur commented on sachem/Views/Inscription/Index.cshtml
> +.checkzone{width:25px;top:-1px;height:25px;background-size:100%; }
mettre sur plusieurs lignes pour rendre le CSS plus lisible : 
```
.checkzone
{
    width:25px;
    top:-1px;
    height:25px;
    background-size:100%; 
}
```

2016-12-02 14:17 UTC, olafleur commented on sachem/Views/Jumelage/Details.cshtml
> +            @Html.Label("[WIP FORMULAIRE] Reponse - 3hrs")
WIP ? ;)

2016-12-02 14:17 UTC, olafleur commented on sachem/Views/Jumelage/_JumelagesAvec.cshtml
> +@if (listeJumeleurs.Count()>0)
`@if (listeJumeleurs.Count() > 0)`

2016-12-02 14:18 UTC, olafleur commented on sachem/Views/Parametres/EditCollege.cshtml
> +<a onclick=" AjoutModal();" href="#" data-toggle="modal" data-target="#modalAjout" class="btn btn-default" style="margin-top:5px;margin-bottom:15px;">Ajouter un collège d'enseignement</a>
?

2016-12-02 14:20 UTC, jwallet commented on sachem/Views/Parametres/EditCollege.cshtml
> +<a onclick=" AjoutModal();" href="#" data-toggle="modal" data-target="#modalAjout" class="btn btn-default" style="margin-top:5px;margin-bottom:15px;">Ajouter un collège d'enseignement</a>
cetait pas voulu ca

2016-12-02 14:21 UTC, jwallet commented on sachem/Views/Jumelage/Details.cshtml
> +            @Html.Label("[WIP FORMULAIRE] Reponse - 3hrs")
cest du code qui demande des foncitonnalites quon a pas developper encore

2016-12-02 14:40 UTC, jwallet requested changes

2016-12-02 14:40 UTC, jwallet commented on sachem/Controllers/InscriptionController.cs
> +            List<string> Jours = new List<string>();
Ouuuuuu
la liste de string peut etre remplacer par le enum fait dans controller jumelage, et tu transforme ton int en enum string. le enum est deja integrer a nos controllers, vous l'utilisez plus bas.
`(Semaine)i;`
```List<string> jours = new List<string>();
for(int i=1; i<6; i++)
{
    jours.add((Semaine)i.ToString());
}
return jours;
```
comme ca on a juste a changer les valeurs du enum

2016-12-02 14:40 UTC, jwallet commented on sachem/Controllers/InscriptionController.cs
> +            int EntriesCount = 18;
constant int HEURE_FIN

2016-12-02 14:40 UTC, jwallet commented on sachem/Controllers/InscriptionController.cs
> +                double heureCheckbox = e.Key.TotalMinutes - StartTime.TotalMinutes;
`double heureCheckbox = e.Key.TotalMinutes;`
le systeme doit etre sur 24hrs, donc 8h = 480, comme indique a Alex hier. si sachem decide de commencer les rencontres a 9h ou a 7h, toute les dispos dans bd des etudiants vont decaler, pas bien,

2016-12-02 14:40 UTC, jwallet commented on sachem/Models/DisponibiliteStruct.cs
> +            dictionary = new Dictionary<string, int>();
Ouuuuuu
la liste de string peut etre remplacer par le enum fait dans controller jumelage, et tu transforme ton int en enum string. le enum est deja integrer a nos controllers, vous l'utilisez plus bas.
`(Semaine)i;`
```List<string> jours = new List<string>();
for(int i=1; i<6; i++)
{
    jours.add((Semaine)i.ToString());
}
return jours;
```
comme ca on a juste a changer les valeurs du enum

2016-12-02 15:00 UTC, olafleur commented on sachem/Models/DisponibiliteStruct.cs
> +                , { "Mercredi", 4 }, { "Jeudi", 5 }, { "Vendredi", 6 } };
On fait habituellement le saut de ligne **après** la virgule

2016-12-02 15:13 UTC, olafleur commented on sachem/Web.config
> +    <add name="SACHEMEntities" connectionString="metadata=res://*/Models.Model1.csdl|res://*/Models.Model1.ssdl|res://*/Models.Model1.msl;provider=System.Data.SqlClient;provider connection string=&qu
Ah oui ?

2016-12-02 15:38 UTC, jwallet approved these changes

2016-12-02 15:39 UTC, jwallet commented on sachem/Web.config
> +    <add name="SACHEMEntities" connectionString="metadata=res://*/Models.Model1.csdl|res://*/Models.Model1.ssdl|res://*/Models.Model1.msl;provider=System.Data.SqlClient;provider connection string=&qu
ah si

2016-12-02 15:45 UTC, jwallet requested changes

2016-12-02 15:45 UTC, jwallet commented on sachem/Models/DisponibiliteStruct.cs
> +            dictionary.Add("Vendredi", 6);
a quoi sa vous sert d'avoir un dictionnaire qui fait la meme chose que le enum Semaine.
prenez votre jour et fait un parse au enum.
pourrait etre supprimer
```dictionary = new Dictionary<string, int> { { "Lundi", 2 }, { "Mardi", 3 },
 +                { "Mercredi", 4 }, { "Jeudi", 5 }, { "Vendredi", 6 } };
 +            dictionary = new Dictionary<string, int>();
 +            dictionary.Add("Lundi", 2);
 +            dictionary.Add("Mardi", 3);
 +            dictionary.Add("Mercredi", 4);
 +            dictionary.Add("Jeudi", 5);
 +            dictionary.Add("Vendredi", 6);
```

2016-12-02 15:45 UTC, olafleur commented on sachem/Controllers/InscriptionController.cs
> +        //[ValidationAcces.ValidationAccesInscription]
!!

2016-12-02 15:46 UTC, olafleur commented on sachem/Controllers/InscriptionController.cs
> +        //[ValidationAcces.ValidationAccesInscription]
!!

2016-12-02 15:48 UTC, jwallet commented on sachem/Controllers/InscriptionController.cs
> +                    dispoBD.id_Jour = m.dictionary[m.Jour];
```dispoBd.id_Jour = (int)Enum.Parse(typeof(Semaine), jour);```

2016-12-02 15:50 UTC, jwallet commented on sachem/Controllers/InscriptionController.cs
> +        //[ValidationAcces.ValidationAccesInscription]
jumelage est en developpement encore, les autres ont fini et veulent merger, mais je continue sur la branche, le commentaire me permet d'aller tester plus vite

2016-12-02 17:40 UTC, jwallet reviewed
fixed #72

2016-12-02 17:59 UTC, olafleur commented on sachem/Content/Site.css
>  }
nl eof

2016-12-02 18:06 UTC, olafleur commented on sachem/Controllers/InscriptionController.cs
>          //[ValidationAcces.ValidationAccesInscription]
code en commentaire !

2016-12-02 18:06 UTC, olafleur commented on sachem/Controllers/InscriptionController.cs
> +        //[ValidationAcces.ValidationAccesInscription]
!!!

2016-12-02 18:10 UTC, jwallet commented on sachem/Content/Site.css
>  }
quoi

2016-12-02 18:12 UTC, olafleur commented on sachem/Content/Site.css
>  }
New Line at End Of File. Github te le dit, ça te prend une nouvelle ligne à la fin de chaque fichier. :)

2016-12-02 18:15 UTC, jwallet approved these changes

2016-12-02 18:21 UTC, jwallet commented
close issue #56 , #72

2016-12-02 19:00 UTC, Gogluness commented on sachem/Classes_Sachem/ValidationsAcces.cs
> +                var Session = db.Session.GroupBy(s => s.id_Sess).Select(s => s.OrderByDescending(c => c.id_Sess).First()).Select(c => new { c.id_Sess}); ;
`List.Last(x => x.something)` devrais pouvoir remplacer `OrderByDescending().First()`

2016-12-02 19:00 UTC, Gogluness commented on sachem/Controllers/InscriptionController.cs
> +        private const int DUREE_RENCONTRE = 90;
On devrait indiquer les unités ici. soit dans le nom de la variable ou dans un petit commentaire. Parce que 90 heure c,est long en Ca#*&?

2016-12-02 19:00 UTC, Gogluness commented on sachem/Controllers/InscriptionController.cs
> +        public ActionResult Index(int typeInscription, string[] jours )
Une méthode Index qui fait autre chose que retourner la vue c'est mal mvoyez
![xayccf](https://cloud.githubusercontent.com/assets/8545744/20845582/c44285ee-b893-11e6-9338-3054343e1668.jpg)

2016-12-02 19:00 UTC, Gogluness commented on sachem/Controllers/InscriptionController.cs
> +        }
Une méthode de 60 lignes c'est méga énorme. Small functions are better functions

2016-12-02 19:00 UTC, Gogluness commented on sachem/Controllers/InscriptionController.cs
> +            Inscription inscriptionBD = new Inscription();
Aller regarder les Object Initialisers
https://msdn.microsoft.com/fr-ca/library/bb384062.aspx

2016-12-02 19:00 UTC, Gogluness commented on sachem/Controllers/InscriptionController.cs
> +                    case 1: // élève aidé
Des constantes ou un enum, please

2016-12-02 19:00 UTC, Gogluness commented on sachem/Controllers/InscriptionController.cs
> +            foreach (var e in Entree)
e wut? Toujours utiliser des noms significatifs

2016-12-02 19:00 UTC, Gogluness commented on sachem/Controllers/InscriptionController.cs
> +                double heureCheckbox = e.Key.TotalMinutes;
il faut faire une distinction entre le frontend et le backend. Les nom de variable ne devrais jamais référencer des concept qui appartiennent au frontend.

2016-12-02 19:00 UTC, Gogluness commented on sachem/Controllers/InscriptionController.cs
> +                e.Key.Hours + "h" + e.Key.Minutes.ToString("00") + "-" + e.Value.Hours + "h" + e.Value.Minutes.ToString("00"),
String.Format

2016-12-02 19:00 UTC, Gogluness commented on sachem/Views/Inscription/Index.cshtml
> +        var modal = document.getElementById('ConfirmDisp');
Utiliser jQuery

2016-12-02 19:00 UTC, Gogluness commented on sachem/Views/Inscription/Index.cshtml
> +        var typeinscr = $('#TypeInscription').val();
PascalCase ou camelCase

2016-12-02 19:00 UTC, Gogluness commented on sachem/Views/Jumelage/Delete.cshtml
> +    @using (Html.BeginForm("Delete", "Jumelage", FormMethod.Post, new { @class = "form-inline", role = "form" }))
Pour supprimer quelque chose Toujours utiliser HttpDelete

2016-12-02 19:00 UTC, Gogluness commented on sachem/Views/Jumelage/_JumelagesPossibles.cshtml
> +        document.getElementById('modal-tuteur').textContent = nomTuteur;
always use jQuery

2016-12-02 19:02 UTC, DylanMarcotte commented on sachem/Controllers/InscriptionController.cs
> +        public ActionResult Index(int typeInscription, string[] jours )
C'est dans le POST tho?

2016-12-02 19:04 UTC, DylanMarcotte commented on sachem/Controllers/InscriptionController.cs
> +                e.Key.Hours + "h" + e.Key.Minutes.ToString("00") + "-" + e.Value.Hours + "h" + e.Value.Minutes.ToString("00"),
Pourquoi utiliser un format quand le String peut être construit en soit sans méthode? Alourdissement de code non?

2016-12-02 19:04 UTC, DylanMarcotte commented on sachem/Views/Inscription/Index.cshtml
> +        var modal = document.getElementById('ConfirmDisp');
"$.each(postData.jours, function (nom, disp) {"
Thats JQuery

2016-12-02 19:05 UTC, DylanMarcotte commented on sachem/Views/Inscription/Index.cshtml
> +        var modal = document.getElementById('ConfirmDisp');
Pourquoi? C'est dans le DOM?

2016-12-02 19:05 UTC, olafleur commented on sachem/Controllers/InscriptionController.cs
> +        public ActionResult Index(int typeInscription, string[] jours )
Oui, mais ça veut probablement dire que le nom `Index` n'est pas significatif dans ce contexte.

2016-12-02 19:11 UTC, DylanMarcotte commented on sachem/Views/Jumelage/Delete.cshtml
> +    @using (Html.BeginForm("Delete", "Jumelage", FormMethod.Post, new { @class = "form-inline", role = "form" }))
C'est un controller, pas une méthode delete

2016-12-02 19:29 UTC, olafleur commented on sachem/Views/Jumelage/Delete.cshtml
> +    @using (Html.BeginForm("Delete", "Jumelage", FormMethod.Post, new { @class = "form-inline", role = "form" }))
Ça pourrait être renommé en DeletePage ou de quoi du genre.

2016-12-08 13:19 UTC, louisrochtessier approved these changes

2016-12-08 15:19 UTC, cristianzubieta approved these changes

2016-12-08 18:31 UTC, merged